### ISSUE TITLE
AES CBC is producing different result when encrypting the same string with the same key

### ISSUE THREAD

**Issue by ionutale** [brix/crypto-js#234] opened 2019-10-01 09:28 UTC
AES CBC is producing different result when encrypting the same **string-data** with the same **key** (password):

`
{
	"password": "secretkey",
	"data": "very important data"
}
`

run 1: `U2FsdGVkX19FrkhtU0z3wgHQ7wawStvpe2onu4LbT0g7RcUejKS714z34a6lONOE`

run 2: `U2FsdGVkX1+fli14tUL6NurpYVRW4Cp6PUqhUOEBOrSxMYgMVRTbc5vwmYO5TwX/`

run 3: `U2FsdGVkX18xpwj2RIt3Qz7qtS0kNv4ZF/XRoDCRDsC1JgzNSAfGZsUNt1/bjkvM`

run 4: `U2FsdGVkX19fi+SOVjcO/2bR5VqjhOyvJS1B+z/xJ5DVDnnqby+6/6kEaM+n6Vmz`

run 5: `U2FsdGVkX18toNL/PAiClfBW3C8xa+41IiSL5b0Vi4HD2it1ExyeDGfyTyZu2yuG`

is this the way it suppose to work?

**Comment by TobiasWen** [comment] 2019-10-22 10:26
I don't have any knowledge about the implementation in crypto-js but normally each AES CBC encryption starts with a randomly generated initialization vector for the first block encryption. The result is then used as initialization vector for the next block. So in fact the ciphertexts never should be the same.

**Comment by blankey1337** [comment] 2019-11-28 18:24
This is due to it having a salt, totally expected.

**Comment by max-lai** [comment] 2020-01-09 18:05
Duplicate of #217

**Closed as completed** 2020-01-17 16:50 UTC
