### ISSUE TITLE
Error: Native crypto module could not be used to get secure random number.

### ISSUE THREAD

**Issue by harendra-iitg** [brix/crypto-js#258] opened 2020-02-11 13:52 UTC
I get this issue when i try to run yarn dev
```		
crypto-js: "^3.1.9-1",
```
this is my crypto version in package . how to fix it ?

**Comment by debugrammer** [comment] 2020-02-11 13:59
> I get this issue when i try to run yarn dev
> 
> ```
> crypto-js: "^3.1.9-1",
> ```
> 
> this is my crypto version in package . how to fix it ?

You can remove `^`

```
crypto-js: "3.1.9-1",
```

and type `yarn install` for rolling back your `crypto-js` version to `3.1.9-1`.

**Comment by evanvosberg** [comment] 2020-02-11 17:21
Duplicate of this issue https://github.com/brix/crypto-js/issues/256

**Closed as completed by evanvosberg** 2020-02-11 17:21 UTC
Labels: duplicate
